  version: '3.1'
  services:
    postgresqldb:
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=cristal
        - POSTGRES_USER=cristal
        - POSTGRES_DB=postgres
      volumes:
        - ./src/main/resources/postgres_testdata:/var/lib/postgres