  version: '3.1'
  services:
    app:
      container_name: refinaria-postgresql
      image: postgres
      ports:
        - "8080:8080"
    postgresqldb:
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=cristal
        - POSTGRES_USER=cristal
        - POSTGRES_DB=postgres