jwt:
  secret: secretkey123

spring:
  datasource:
    url: ${JDBC_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    driver-class-name: org.postgresql.Driver
    username: cristal
    password: cristal
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database: POSTGRESQL
    datasource:
      plataform: postgres
    show-sql: true
    generate-ddl: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: cristalacademysdg@gmail.com
    password: ${EMAIL_PASS:12345}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

refpath:
  swagger:
    path: localhost:8080
    apiinfo:
      title: "Refinaria API"
      description: "Sistema de refinaria para nivelamento de candidatos"
      termsOfServiceUrl: "http://localhost:8080"
      license: ""
      licenseUrl: "http://localhost:8080"
      version: "2.0"

api:
  links:
    host: ${FRONT_HOST:http://localhost:4200}
    recuperar-senha: ${api.links.host}/recuperar-senha